import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Sidebar from "@/components/Sidebar/Sidebar";
import { Content } from "@/components/ui/content-wrapper";
import { UserProvider } from "@/context/userContext";
import { DataProvider } from "@/context/dataContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Spark-Hub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div
      className={`${geistSans.variable} ${geistMono.variable}  bg-background-2 antialiased grid grid-cols-[200px_1fr] gap-4 p-4`}
      style={{ overscrollBehavior: "none" }}
    >
      <UserProvider>
        <DataProvider>
          <Sidebar></Sidebar>
          <Content>{children}</Content>
        </DataProvider>
      </UserProvider>
    </div>
  );
}
