import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Sidebar from "@/components/Sidebar/Sidebar";
import { Content } from "@/components/Content/Content";
import { UserProvider } from "@/context/userContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Spark-Hub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-gray-100 antialiased grid grid-cols-[200px_1fr] gap-4 m-4  `}
        style={{ overscrollBehavior: "none" }}
      >
        <UserProvider>
          <Sidebar></Sidebar>
          <Content>{children}</Content>
        </UserProvider>
      </body>
    </html>
  );
}
