import type { Metadata } from "next";
import "../globals.css";
import { Footer } from "@/components/ui/footer";

export const metadata: Metadata = {
  title: "Spark-Hub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="h-[calc(100%+40px)] w-full">
      {children}
      <Footer></Footer>
    </div>
  );
}
